apiVersion: v1
kind: Config
preferences: {}

# Define the cluster
clusters:
- cluster:
    certificate-authority-data: <PLACE_CERTIFICATE_HERE>
    # You'll need the API endpoint of your Cluster here:
    server: https://<YOUR_KUBERNETES_API_ENDPOINT>
  name: my-cluster

# Define the user
users:
- name: mynamespace-user
  user:
    as-user-extra: {}
    client-key-data: <PLACE_CERTIFICATE_HERE>
    token: <PLACE_USER_TOKEN_HERE>

# Define the context: linking a user to a cluster
contexts:
- context:
    cluster: my-cluster
    namespace: mynamespace
    user: mynamespace-user
  name: mynamespace

# Define current context
current-context: mynamespace